set(patch_target "${DYNCALL_SRC}")
set(old "if(MSVC)")
set(new "if(MSVC AND NOT CMAKE_CXX_COMPILER_ID STREQUAL \"Clang\")")
foreach(rel_file CMakeLists.txt dyncall/CMakeLists.txt dyncallback/CMakeLists.txt)
  set(f "${patch_target}/${rel_file}")
  file(READ "${f}" content)
  string(REPLACE "${old}" "${new}" content "${content}")
  file(WRITE "${f}" "${content}")
endforeach()
