#pragma once

#include <stdint.h>

/* Stable opcodes for the Lamina Runtime -> LMCAS construction boundary. */
typedef enum LmExprUnaryOp {
    LMX_EXPRESSION_OPERATION_NEG = 0,
    LMX_EXPRESSION_OPERATION_NOT = 1,
} LmExprUnaryOp;

typedef enum LmExprBinaryOp {
    LMX_EXPRESSION_OPERATION_ADD = 0,
    LMX_EXPRESSION_OPERATION_SUB = 1,
    LMX_EXPRESSION_OPERATION_MUL = 2,
    LMX_EXPRESSION_OPERATION_DIV = 3,
    LMX_EXPRESSION_OPERATION_POW = 4,
    LMX_EXPRESSION_OPERATION_EQ = 5,
    LMX_EXPRESSION_OPERATION_NE = 6,
    LMX_EXPRESSION_OPERATION_GT = 7,
    LMX_EXPRESSION_OPERATION_GE = 8,
    LMX_EXPRESSION_OPERATION_LT = 9,
    LMX_EXPRESSION_OPERATION_LE = 10,
    LMX_EXPRESSION_OPERATION_AND = 11,
    LMX_EXPRESSION_OPERATION_OR = 12,
    LMX_EXPRESSION_OPERATION_IN = 13,
    LMX_EXPRESSION_OPERATION_NOT_IN = 14,
} LmExprBinaryOp;
